on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build
    - run: |
        gh release create --prerelease -- "$tag" || gh api -X PATCH "/repos/{owner}/{repo}/git/refs/tags/$tag" -F force=true -f "sha=$(git rev-parse @)"
        gh release upload --clobber -- "$tag" *.iso
      env:
        tag: ${{github.ref_name}}-nightly
        GH_TOKEN: ${{github.token}}
