on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build
    - uses: softprops/action-gh-release@v1
      with:
        files: image.iso
        tag_name: ${{github.ref_name}}-nightly
        prerelease: true
        target_commitish: ${{github.sha}}
